import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={styles.header}>
        <p>
          <a href='/'>
            Martin Fuglset
          </a>
          <a>Lights off</a>
          <a>Menu</a>
        </p>
      </header>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Portfolio
        </h1>

        <div className={styles.grid}>
          <a href="/cv" className={styles.card}>
            <h2>CV</h2>
            <p>CV</p>
          </a>

          <a href="/projects" className={styles.card}>
            <h2>Projects</h2>
            <p>Project 1</p>
          </a>

          <a
            href="abilities"
            className={styles.card}
          >
            <h2>Abilities</h2>
            <p>Python</p>
          </a>

        </div>
      </main>

      <footer className={styles.footer}>
        <div className={styles.grid}>
        <a href='mailto:fuglsetm@gmail.com'>
          Email 
        </a>
        <a href='https://github.com/Martinfuglset'>
          GitHub 
        </a>
        <a href='https://www.linkedin.com/in/martinfuglset/'>
          LinkedIn
        </a>
        </div>
      </footer>
    </div>
  )
}
